# $schema: https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
reviews:
  profile: chill
  review_status: true
  high_level_summary: true
  request_changes_workflow: true
  poem: false
  auto_review:
    enabled: true
    drafts: false
