# $schema: https://json.schemastore.org/codecov.json
coverage:
  status:
    project:
      default:
        target: 0.8

comment:
  behavior: default
  layout: "files, diff, uncovered"
  require_base: false
  require_changes: false
