spring:
  main:
    banner-mode: off
    keep-alive: true
    log-startup-info: false
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  ssl:
    bundle:
      pem:
        https:
          reload-on-update: true
          keystore:
            certificate: "file:${NEMO_HTTPS_CERTIFICATE}"
            private-key: "file:${NEMO_HTTPS_CERTIFICATE_KEY}"
  datasource:
    url: "jdbc:h2:./build/nemo.db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE"
    username: "sa"
    password: ""
  liquibase:
    change-log: "classpath:db/changelog/_main.yaml"
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: jcache
      hibernate.javax.cache.provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider

server:
  shutdown: graceful
  port: ${NEMO_PORT:8443}
  ssl:
    bundle: https
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    root: warn
    nemo: info
  charset:
    file: UTF-8
    console: UTF-8
  pattern:
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] %-36.36logger{36}: [%5p] %m%n%wEx"
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %clr(%-36.36logger{36}){cyan}: [%clr(%5p)] %m%n%wEx"
  file:
    path: ./logs
    name: "${logging.file.path}/nemo.log"
  logback.rollingpolicy:
    total-size-cap: 1GB
    max-file-size: 20MB
    max-history: 365
